version: "3.9"
services:
  foo:
    container_name: "foo"
    image: foo
    build: ./foo
    ports:
      - 8000:8000
  bar:
    container_name: bar
    build: ./bar
    ports:
      - 8033:8000
  nginx:
    container_name: "nginx"
    image: nginx:latest
    ports:
      - "8082:80"
    volumes:
      - ./nginx_config.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - foo
      - bar